### PR TITLE
Allow binding to imposter engine cli rather than imposter-cli

### PR DESCRIPTION
**Pull request by marmotherder**
Allows the running of unit tests or otherwise using the container hosted at: https://hub.docker.com/r/outofcoffee/imposter, without needing additional installs of the CLI, only npm.

### CODE REVIEW

**Comment by pcornish** [comment]
This is a good idea @marmotherder - thank you. Presume the `imposter` command that this targets is the shell script shim under `/usr/local/bin` in the image?

**Comment by outofcoffee** [comment]
This is a good idea @marmotherder - thank you. Presume the `imposter` command that this targets is the shell script shim under `/usr/local/bin` in the image?

**Comment by marmotherder** [comment]
That's right @outofcoffee. It does assume that the script is available in PATH given it reuses the "imposter" command we would see with the CLI.

Worth getting some unit tests in there as well thinking about it. I was able to run tests on a local imposter setup no issue, but given where this is impacting, we should try to prove it.

**Comment by marmotherder** [comment]
@outofcoffee, I've made a small tweak to the tests for version, and updated CI to have another job, just to run tests in the docker container. Got it to run successfully against my fork: https://github.com/marmotherder/imposter-js/actions/runs/1480851935

**Comment by outofcoffee** [comment]
Hi @marmotherder - thanks again for the suggestion. As of [v2.1.0](https://github.com/outofcoffee/imposter/blob/main/CHANGELOG.md#210---2021-11-23) the Docker images include the CLI, preconfigured for use with the JVM distro.

Are you happy for us to close this PR?

**Comment by marmotherder** [comment]
@outofcoffee that fits the use case here for me at least, happy to close the PR here in that case.

**Pull request closed without merging**
